name: Android build
on:
  push:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Build APK
        run: |
          ./gradlew assembleGitDebug
          mv app/build/outputs/apk/git/debug/app-git-debug.apk CS16Client-Android.apk
        working-directory: android
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android
          path: android/CS16Client-Android.apk
          
